---
# defaults file for django-uwsgi-systemdU
UWSGI_SYSTEMD_SERVICE: "{{DJANGO_APP_NAME}}"
UWSTI_PROCESSES: 4
UWSGI_PYTHONPATH: "{{DJANGO_APPLICATION_CHECKOUT_DIR}}"
UWSGI_FOLDER: "{{DJANGO_APP_USER_HOME}}/uwsgi"
UWSGI_CONFIG_FILE: "{{UWSGI_FOLDER}}/{{DJANGO_APP_NAME}}-uwsgi.ini"
UWSGI_PIDFILE: "{{UWSGI_FOLDER}}/pid"
UWSGI_SOCKET: "{{UWSGI_FOLDER}}/socket"
UWSGI_MODULE: null


DJANGO_APPLICATION_SYSTEMD_ENV_FILE: "/etc/{{DJANGO_APP_NAME}}.env"
VIRTUALENV_COMMAND: "{{python.location}}/bin/pyvenv"
