---
# tasks file for django-nginx

- name: install deps
  apt: name={{ item }} state=present
  with_items: "{{ NGINX_REQUIRED_PACKAGES }}"
  notify: restart ngingx

- name: remove default site
  file: name=/etc/nginx/sites-enabled/default state=absent
  notify: restart ngingx

- name: template http site
  template:
    src: nginx-site-http
    dest: /etc/nginx/sites-enabled/{{ NGINX_SITE_NAME }}
  when: "{{ not NGINX_USE_HTTPS }}"
  notify: restart ngingx